### ISSUE TITLE
SFE breaks asm.js validity && code

### ISSUE THREAD

**Issue by caiiiycuk** [achoudhury85/Similar-Function-Elimination#3]
Hi Arnab. I found way to reproduce asm.js validity error. Please use roll-a-ball project from unity: 
[roll-a-ball.zip](https://github.com/achoudhury85/Similar-Function-Elimination/files/1246506/roll-a-ball.zip)

This is compiled version of project (nothing modified, release build with gzip off). Important files:
```
index.html - unity template for browser
Build/roll-a-ball.asm.code.unityweb - code of roll-a-ball
```

So you can run it in browser:
```
firefox index.html
```
You should see just a play area (plane). Also if you open dev tools you will see that asm.js is valid.

Now you can try to use SFE on it:
```
node --max-old-space-size=8192  run_sfe.js --file roll-a-ball.asm.code.unityweb.backup > roll-a-ball.asm.code.unityweb
```

Size is less but asm.js is invalid and game start with error (like in my NDA project):
```
TypeError: asm.js type error: void incompatible with previous return of type f32
```

Important thing that not only asm.js is non valid, but game does not start, because of error.

**Comment by achoudhury85** [comment]
Thanks caiiiycuk! I will use this and fix soon. Thanks for the due diligence.

**Comment by caiiiycuk** [comment]
May be you need also symbols:
[build.js.symbols.zip](https://github.com/achoudhury85/Similar-Function-Elimination/files/1246645/build.js.symbols.zip)

**Comment by achoudhury85** [comment]
Hello @caiiiycuk - just wanted to provide you with an update here - still debugging through a few issues here. Will have a more detailed update tomorrow.

**Comment by caiiiycuk** [comment]
Thank you. No rush :)

**Comment by achoudhury85** [comment]
Hello @caiiiycuk - I can confirm that the issue is now fixed with the latest commit:

https://github.com/achoudhury85/Similar-Function-Elimination/commit/59350877091d5de6948bdb7189a4f4f554449421

Can you confirm, and if everything looks good, close out? Thanks!

**Comment by caiiiycuk** [comment]
Yes, I can confirm that problem is solved both in Roll-a-ball and in NDA project.
Thank you so much!
