### ISSUE TITLE
SFE produces invalid asm.js (Chrome)

### ISSUE THREAD

**Issue by caiiiycuk** [achoudhury85/Similar-Function-Elimination#4]
Hi! I using your tool, it's very good. But I found another problem with unity project. I attach archive with compiled unity [game](https://www.assetstore.unity3d.com/en/#!/content/11228). 

[Archive.zip](https://github.com/achoudhury85/Similar-Function-Elimination/files/1421661/uplatformer.zip) content:
Build/bin.asm.code.unityweb.backup - original js file
Build/bin.asm.code.unityweb - optimized by sfe
testing-unity.html - page to run in browser

When you run 'testing-unity.html' in chrome you will see error 'Invalid asm.js: Unexpected token'. But FF says that successfully compiled asm.js

Can you verify is this an chrome bug, can sfe avoid this error?

**Comment by caiiiycuk** [comment]
Looks like it's a google chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=764956

**Comment by achoudhury85** [comment]
Awesome, thanks @caiiiycuk!

**Comment by caiiiycuk** [comment]
BTW, I found workaround:
```
sed -i "s/\([A-Za-z$]\)<<2>>2/(\\1<<2)>>2/ig" bin.asm.code.unityweb
```
chrome can't parse this expression `$<<2>>2`, probably any kind of `[A-Za-z]<<\d>>\d`. Is it possible to add parenthesis as workaround? `($<<2)>>2`

**Comment by achoudhury85** [comment]
Hey @caiiiycuk , we could add this type of conversion to the asmJSComplianceChecker. Feel free to try making the change, I can code review and merge if that works.

**Comment by caiiiycuk** [comment]
I will try!)

**Comment by caiiiycuk** [comment]
I'am not very familiar with esprima. But at first look this problem is produced by esprima not by sfe. escodegen does not have option to generate parentheses in this case. This problem can't be solved by the asmJSComplianceChecker, because it works only on sfe functions. To solve need to implement additional step on whole AST that add verbatim for this nodes. I'am not sure that it's correct solution, looks like overkill.

**Comment by caiiiycuk** [comment]
Correct bug link https://bugs.chromium.org/p/chromium/issues/detail?id=781123
